version: '3.8'

services:
  # Service for your FastAPI application
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
  # Service for the Redis database
  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"